=== elodina/xml-avro/src/test/resources/books.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bks="urn:books" targetNamespace="urn:books">
    <xsd:element name="books" type="bks:BooksForm"/>
    <xsd:complexType name="BooksForm">
        <xsd:sequence>
            <xsd:element name="book" type="bks:BookForm" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="BookForm">
        <xsd:sequence>
            <xsd:element name="author" type="xsd:string"/>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="genre" type="xsd:string"/>
            <xsd:element name="price" type="xsd:float"/>
            <xsd:element name="pub_date" type="xsd:dateTime" minOccurs="0"/>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element name="review" type="xsd:string"/>
                <xsd:element name="alias" type="bks:AliasType"/>
                <xsd:element name="website" type="bks:WebsiteType"/>
            </xsd:choice>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="AliasType">
        <xsd:sequence>
            <xsd:element name="alias_name" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="WebsiteType">
        <xsd:sequence>
            <xsd:element name="web_url" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== elodina/xml-avro/src/test/resources/books.xml
<?xml version="1.0"?>
<x:books xmlns:x="urn:books" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="urn:books books.xsd">
    <book id="bk001">
        <author>Writer</author>
        <title>The First Book</title>
        <genre>Fiction</genre>
        <price>44.95</price>
        <pub_date>2015-09-08T10:46:43+02:00</pub_date>
        <review>An amazing story of nothing.</review>
        <review>Sample Review</review>
        <review>Sample Story</review>
        <alias>
            <alias_name>Crap 1</alias_name>
            <alias_name>Crap 2</alias_name>
        </alias>
        <website>
            <web_url>amazon</web_url>
            <web_url>flipkart</web_url>
            <web_url>ebay</web_url>
            <web_url>facebook</web_url>
        </website>
    </book>
	<book id="bk001">
        <author>Writer</author>
        <title>The First Book</title>
        <genre>Fiction</genre>
        <price>44.95</price>
        <pub_date>2015-09-08T10:46:43+02:00</pub_date>
        <review>An amazing story of nothing.</review>
        <alias>
            <alias_name>Crap 1</alias_name>
            <alias_name>Crap 2</alias_name>
        </alias>
        <website>
            <web_url>amazon</web_url>
            <web_url>flipkart</web_url>
            <web_url>ebay</web_url>
            <web_url>facebook</web_url>
        </website>
    </book>
    <book id="bk002">
        <author>Poet</author>
        <title>The Poet's First Poem</title>
        <genre>Poem</genre>
        <price>24.95</price>
        <review>Least poetic poems.</review>
        <alias>
            <alias_name>Book Made in China</alias_name>
            <alias_name>Book made in italy</alias_name>
        </alias>
        <website>
            <web_url>amazon</web_url>
            <web_url>alibaba</web_url>
        </website>
    </book>
</x:books>
